### ISSUE TITLE
Long titles keep showing under the title

### ISSUE THREAD

**Issue by DocPoke** [CringyAdam/CringyBrowser#1]
Example: ![image](https://cloud.githubusercontent.com/assets/19578675/26214463/2750a9be-3c05-11e7-8f4a-75afe8cd5b31.png)

**Comment by CringyAdam** [comment]
lemme debug dis

**Comment by CringyAdam** [comment]
It's not a bug. It's a feature.
*~Cringy Adam, 2k17.*
